# Generated by Django 3.2.13 on 2022-06-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='covTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(blank=True, max_length=30, null=True, verbose_name='项目名称')),
                ('projectId', models.IntegerField(blank=True, null=True, verbose_name='所属项目ID')),
                ('covTaskName', models.CharField(blank=True, max_length=30, null=True, verbose_name='任务名称')),
                ('branch', models.CharField(blank=True, max_length=100, null=True, verbose_name='被测分支')),
                ('compareBranch', models.CharField(blank=True, max_length=100, null=True, verbose_name='基准分支(对比分支)')),
                ('status', models.CharField(blank=True, max_length=30, null=True, verbose_name='状态：0新建，1clone完成，2clone异常')),
                ('deleted', models.IntegerField(blank=True, default='0', null=True, verbose_name='是否删除')),
                ('startTime', models.DateTimeField(blank=True, null=True, verbose_name='搜集覆盖率开始时间')),
                ('endTime', models.DateTimeField(blank=True, null=True, verbose_name='搜集覆盖率结束时间')),
                ('lastCollectTime', models.DateTimeField(blank=True, null=True, verbose_name='上次收集时间')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=20, verbose_name='项目名称')),
                ('gitURL', models.CharField(max_length=255, verbose_name='git地址：形如gitee.com/xxx/yyy.git')),
                ('gitName', models.CharField(max_length=255, verbose_name='git登录名')),
                ('gitPwd', models.CharField(max_length=255, verbose_name='git密码')),
                ('deleted', models.IntegerField(default='0', verbose_name='是否删除')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
    ]
